// After each quote, the next element is to define if it's a 'favourite' quote, the last is to define if it's NSFW.
export const quoteList = [
["Are midnight snacks only for the weak?", 0, 0],
["Are you a heartbreaker?", 0, 0],
["Are you going to judge me if I tell you I don't mind a loud shirt?", 0, 0],
["Are you Smexy (I.E. Smart and Sexy)?", 0, 1],
["Best sleep you had?", 0, 0],
["Can you really say youre married until you've crossed streams?", 0, 1],
["Can you remember your ex partners' birthdays?", 0, 0],
["Could you ever kill a litter of puppies to put them out of their misery? (they're very sick)", 0, 0],
["Describe a time when you were a bit miffed.", 0, 0],
["Describe the taste of coffee", 0, 0],
["Do you enjoy something less when you realise you're using/consuming an Aldi brand-clone?", 0, 0],
["Do you hate or rate Harvester restaurants", 0, 0],
["Do you have a favourite TV advert?", 0, 0],
["Ever broken a bone?", 1, 0],
["Everybody gets to mess up once. Have you already?", 1, 0],
["Exactly how many boys' does Kelis' milkshake bring to the yard?", 0, 0],
["Favourite analogue clock face time (both AM and PM)?", 0, 0],
["Favourite zone on the underground (1-9)?", 0, 0],
["Gherkins in burgers, what say you", 0, 0],
["Got any power trousers?", 0, 0],
["Have you ever edited a wiki article?", 0, 0],
["Have you ever fainted?", 0, 0],
["Have you ever met someone English who hasn't been to France?", 0, 0],
["Have you ever owned or worn a sleeping cap?", 0, 0],
["Have you ever said *we are SO over* to someone?", 0, 0],
["Have you ever screamed loudly in public?", 0, 0],
["Have you ever touched a monkey?", 0, 0],
["Have you ever tried to rap?", 0, 0],
["Have you slapped anyone?", 1, 0],
["How does the word residue make you feel, in one word?", 0, 0],
["How many dogs is too many dogs to own?", 1, 0],
["How many drinks would Philip Schofield have to buy you before you say 'No more thank you Philip.'", 0, 0],
["How much of a bum nose have you got?", 0, 0],
["How thick do you like your gravy?", 1, 0],
["How tight do someone's trousers need to be before you say something?", 0, 0],
["If you had to carry around a suitcase full of bricks, for £1 per minute, how long would you carry it around for", 0, 0],
["If you were a cannibal who would you eat?", 0, 0],
["If you were a Pokémon, are you currently at your 1st 2nd or 3rd stage of evolution?", 0, 0],
["Is product placement ever acceptable?", 0, 0],
["Least favourite holiday destination?", 0, 0],
["Most interesting creature you've fed by hand?", 0, 0],
["Name something with a creamy middle.", 0, 1],
["On a scale of 1 to 5 what is your resistance to using train toilets?", 1, 0],
["Preferred method of text message input?", 0, 0],
["Preferred visible fraction of the moon?", 0, 0],
["When did you last get properly told off", 0, 0],
["Shag marry kill: The dolmio mum puppet, the dolmio grandad puppet, and a jar of dolmio", 0, 1],
["Talk me through your 2019", 0, 0],
["Talk me through your keys", 0, 0],
["Talk me through your wallet", 0, 0],
["Tell me about a button that's satisfying to press", 0, 0],
["Tell me about when you first had a cigarette", 0, 0],
["Tell me about your worst ever hangover", 0, 0],
["Tell me someone you went to school with an unfortunate name", 0, 0],
["Weapon of choice in a pub brawl?", 0, 0],
["Were you a fan of Dairy Milk with Biscuit?", 0, 0],
["What advice do you have for me?", 0, 0],
["What are your neighbours like?", 0, 0],
["What festivals have you been to in the past 10 years?", 0, 0],
["What is the worst dog breed?", 0, 0],
["What is your stand to sit ratio when enjoying a bag of crisps?", 0, 0],
["What kind of pet would suit the name Winkles?", 0, 0],
["What makes you feel all hot and sick?", 1, 0],
["What makes you feel like half a million dollars?", 0, 0],
["What one piece of advice would you give to people who want to look good?", 0, 0],
["What song should be played to you to distract you from the hideous pain of mangled legs in a pedestrian vs. bus accident?", 0, 0],
["What ten ingredients would be in your ideal super soothing facial mask?", 0, 0],
["What was on your lunchbox at school?", 0, 0],
["What was the warmest embrace you received?", 0, 0],
["What was your favourite thing about Kim Jong Il?", 0, 0],
["What was your favourite thing in the playground?", 0, 0],
["What was your first pub you went on a date to?", 0, 0],
["What was your most memorable disagreement with a bus driver?", 0, 0],
["What was your rudest awakening?", 0, 0],
["What were the last posters you bought before growing out of putting posters on the walls?", 0, 0],
["What would you do or buy if you wanted to seem more mysterious?", 0, 0],
["What would you pay for a full suit of armour?", 0, 0],
["What's an idiom you'd like to use more often?", 0, 0],
["What's beyond the edge of the universe?", 0, 0],
["What's the drunkest you've ever been on public transport?", 0, 0],
["What's the most blood you ever saw?", 1, 0],
["What's the most complicated software you ever had to use?", 1, 0],
["What's the most gorgeous you ever looked?", 0, 0],
["What's the most scared you've ever been?", 0, 0],
["What's the most you ever cost the taxpayer in one go?", 1, 0],
["What's the most you were ever clapped for?", 1, 0],
["What's the most you've ever gambled?", 0, 0],
["What's the physically strongest thing you ever did?", 0, 0],
["What's your biggest regret of this year?", 0, 0],
["What's your favourite non ingestible fluid?", 0, 0],
["What's your favourite thing about Enya?", 0, 0],
["what's your hottest dance move?", 0, 0],
["What's your most inexplicable occurrence?", 0, 0],
["What's your must have roast dinner ingredient?", 0, 0],
["What's your preferred means of being thanked by a bus driver?", 0, 0],
["When did you last share a bed with a friend?", 0, 1],
["When you fly British Airways, how do you feel when they bring around the hot moist towlettes to put on your face?", 0, 0],
["Where or what is the *danger zone* at the end of the *highway*?", 0, 0],
["Which breed of dog enjoys being stroked the most?", 0, 0],
["Which song do you identify with the lyrics of the most?", 0, 0],
["Who do you not regret losing touch with?", 0, 0],
["Who is the most disgusting person you ever worked with?", 0, 1],
["Who is the most embarrassing member of your extended family?", 0, 0],
["Who would you turn down meeting because you're not worthy? I.e. Tom Hanks", 0, 0],
["Who's the biggest bellend in music?", 0, 1],
["Who's upset you this time?", 1, 0],
["Worst boat experience?", 1, 0],
["Would it be weirder if horses barked like dogs or if babies cried in the womb?", 1, 0],
["Would you say you have an expressive face?", 0, 0],
["Would you stay overnight in a creepy grandfather clock shop?", 0, 0],
["Would you stay overnight in a Happy Shopper?", 0, 0],
["Would you swallow a live wasp for £250?", 1, 0],
["You ever get silly with the hot sauce?", 0, 0],
["Your second and third favourite smells? I do NOT want to know your favourite", 0, 0],
["Who is kind of a big deal?", 0, 0],
["Do the Strictly judges really give a shit?", 0, 1],
["What makes you feel like half a million dollars?", 0, 0],
["What's your favourite variant strain?", 0, 0],
["You ever popped a dreadlock in your mouth?", 0, 0],
["What is your preferred means of of low level corporate sabotage?", 0, 0],
["Kidney stones: our crunchiest bodily artefact?", 0, 0],
["Tell me about your unrequited loves. Come on, it's OK you can tell me. Let's go", 0, 0],
["What's the closest you've been to the queen?", 0, 0],
["Is dying while fixing the aerial on your roof a humiliating death?", 0, 0],

];